//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Mouse"",
            ""id"": ""c67a8dd2-4b96-4319-a2b1-965e9395999c"",
            ""actions"": [
                {
                    ""name"": ""MouseLook"",
                    ""type"": ""PassThrough"",
                    ""id"": ""992ea3b7-0a19-433f-aecf-186e409ace14"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0e29ab61-028e-4461-adcb-93753332108b"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""id"": ""ff87feeb-9d7c-4cc1-b880-1e1ecd80d46a"",
            ""actions"": [
                {
                    ""name"": ""TouchDragLook"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ae3b943d-2a06-41b7-bd0c-6027644ac035"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchSingleFire"",
                    ""type"": ""Button"",
                    ""id"": ""2f2fbb29-b5ce-4f7d-9a78-e8ad59b3e212"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchHoldFire"",
                    ""type"": ""Button"",
                    ""id"": ""30178983-5ec3-476a-b34f-e2507df48fb9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ace4b470-70f3-4e8c-9fd7-8e10d49bbc5e"",
                    ""path"": ""<Touchscreen>/touch0/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchDragLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""823f5cee-ec46-4e98-93b3-49737cb95ff0"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchSingleFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""462cd542-5bb5-4bb5-9ed0-df2a8a200722"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchHoldFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerAction"",
            ""id"": ""6ac10a22-eb66-4817-977c-7df08d1d3e6d"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""ba147d4d-ee06-4e8d-a7cc-8bc5e2ae98cd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""86d58439-d1db-4a19-97e2-7b7255c07f6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchDragLook"",
                    ""type"": ""Value"",
                    ""id"": ""a08754a1-3e3c-4a25-ba1b-4b2e50362070"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SingleFire"",
                    ""type"": ""Button"",
                    ""id"": ""0f8ea825-60b8-4f6c-8479-0dc02054a0e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldFire"",
                    ""type"": ""Button"",
                    ""id"": ""54e2c43e-65a3-44d9-8d6b-efe901630d0e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""d612c2f7-28a9-4f60-b33b-fe1aa928320c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f48435c4-cc67-4033-bd02-09549af2fd0a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""16997442-c809-41fa-baf9-72d2272665d4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""794ae715-37d1-48bd-a4c2-3f3aa27596f5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ca649599-dcb3-421e-9976-c46ce1109309"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5dae671b-480f-49a2-a72f-3d158384d286"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d402f5cf-2d21-417e-9034-10d83c368a90"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ea5711b2-5f48-45c7-a804-770561d4e0bc"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00e0e8af-dc3a-428d-8f9d-459f6fe00707"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchDragLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87cd9e89-c720-4554-bb1b-5be8c24975d8"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SingleFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77ebf645-27aa-4b35-9c07-d5b83b13e52b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""645fb17f-4ddb-44a6-8d7d-2b6e6c470298"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Mouse
        m_Mouse = asset.FindActionMap("Mouse", throwIfNotFound: true);
        m_Mouse_MouseLook = m_Mouse.FindAction("MouseLook", throwIfNotFound: true);
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_TouchDragLook = m_Touch.FindAction("TouchDragLook", throwIfNotFound: true);
        m_Touch_TouchSingleFire = m_Touch.FindAction("TouchSingleFire", throwIfNotFound: true);
        m_Touch_TouchHoldFire = m_Touch.FindAction("TouchHoldFire", throwIfNotFound: true);
        // PlayerAction
        m_PlayerAction = asset.FindActionMap("PlayerAction", throwIfNotFound: true);
        m_PlayerAction_Move = m_PlayerAction.FindAction("Move", throwIfNotFound: true);
        m_PlayerAction_Jump = m_PlayerAction.FindAction("Jump", throwIfNotFound: true);
        m_PlayerAction_TouchDragLook = m_PlayerAction.FindAction("TouchDragLook", throwIfNotFound: true);
        m_PlayerAction_SingleFire = m_PlayerAction.FindAction("SingleFire", throwIfNotFound: true);
        m_PlayerAction_HoldFire = m_PlayerAction.FindAction("HoldFire", throwIfNotFound: true);
        m_PlayerAction_Reload = m_PlayerAction.FindAction("Reload", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Mouse
    private readonly InputActionMap m_Mouse;
    private IMouseActions m_MouseActionsCallbackInterface;
    private readonly InputAction m_Mouse_MouseLook;
    public struct MouseActions
    {
        private @PlayerInputActions m_Wrapper;
        public MouseActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseLook => m_Wrapper.m_Mouse_MouseLook;
        public InputActionMap Get() { return m_Wrapper.m_Mouse; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseActions set) { return set.Get(); }
        public void SetCallbacks(IMouseActions instance)
        {
            if (m_Wrapper.m_MouseActionsCallbackInterface != null)
            {
                @MouseLook.started -= m_Wrapper.m_MouseActionsCallbackInterface.OnMouseLook;
                @MouseLook.performed -= m_Wrapper.m_MouseActionsCallbackInterface.OnMouseLook;
                @MouseLook.canceled -= m_Wrapper.m_MouseActionsCallbackInterface.OnMouseLook;
            }
            m_Wrapper.m_MouseActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MouseLook.started += instance.OnMouseLook;
                @MouseLook.performed += instance.OnMouseLook;
                @MouseLook.canceled += instance.OnMouseLook;
            }
        }
    }
    public MouseActions @Mouse => new MouseActions(this);

    // Touch
    private readonly InputActionMap m_Touch;
    private ITouchActions m_TouchActionsCallbackInterface;
    private readonly InputAction m_Touch_TouchDragLook;
    private readonly InputAction m_Touch_TouchSingleFire;
    private readonly InputAction m_Touch_TouchHoldFire;
    public struct TouchActions
    {
        private @PlayerInputActions m_Wrapper;
        public TouchActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @TouchDragLook => m_Wrapper.m_Touch_TouchDragLook;
        public InputAction @TouchSingleFire => m_Wrapper.m_Touch_TouchSingleFire;
        public InputAction @TouchHoldFire => m_Wrapper.m_Touch_TouchHoldFire;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void SetCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterface != null)
            {
                @TouchDragLook.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouchDragLook;
                @TouchDragLook.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouchDragLook;
                @TouchDragLook.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouchDragLook;
                @TouchSingleFire.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouchSingleFire;
                @TouchSingleFire.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouchSingleFire;
                @TouchSingleFire.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouchSingleFire;
                @TouchHoldFire.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouchHoldFire;
                @TouchHoldFire.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouchHoldFire;
                @TouchHoldFire.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouchHoldFire;
            }
            m_Wrapper.m_TouchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @TouchDragLook.started += instance.OnTouchDragLook;
                @TouchDragLook.performed += instance.OnTouchDragLook;
                @TouchDragLook.canceled += instance.OnTouchDragLook;
                @TouchSingleFire.started += instance.OnTouchSingleFire;
                @TouchSingleFire.performed += instance.OnTouchSingleFire;
                @TouchSingleFire.canceled += instance.OnTouchSingleFire;
                @TouchHoldFire.started += instance.OnTouchHoldFire;
                @TouchHoldFire.performed += instance.OnTouchHoldFire;
                @TouchHoldFire.canceled += instance.OnTouchHoldFire;
            }
        }
    }
    public TouchActions @Touch => new TouchActions(this);

    // PlayerAction
    private readonly InputActionMap m_PlayerAction;
    private IPlayerActionActions m_PlayerActionActionsCallbackInterface;
    private readonly InputAction m_PlayerAction_Move;
    private readonly InputAction m_PlayerAction_Jump;
    private readonly InputAction m_PlayerAction_TouchDragLook;
    private readonly InputAction m_PlayerAction_SingleFire;
    private readonly InputAction m_PlayerAction_HoldFire;
    private readonly InputAction m_PlayerAction_Reload;
    public struct PlayerActionActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActionActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerAction_Move;
        public InputAction @Jump => m_Wrapper.m_PlayerAction_Jump;
        public InputAction @TouchDragLook => m_Wrapper.m_PlayerAction_TouchDragLook;
        public InputAction @SingleFire => m_Wrapper.m_PlayerAction_SingleFire;
        public InputAction @HoldFire => m_Wrapper.m_PlayerAction_HoldFire;
        public InputAction @Reload => m_Wrapper.m_PlayerAction_Reload;
        public InputActionMap Get() { return m_Wrapper.m_PlayerAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActionActions instance)
        {
            if (m_Wrapper.m_PlayerActionActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnJump;
                @TouchDragLook.started -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnTouchDragLook;
                @TouchDragLook.performed -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnTouchDragLook;
                @TouchDragLook.canceled -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnTouchDragLook;
                @SingleFire.started -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnSingleFire;
                @SingleFire.performed -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnSingleFire;
                @SingleFire.canceled -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnSingleFire;
                @HoldFire.started -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnHoldFire;
                @HoldFire.performed -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnHoldFire;
                @HoldFire.canceled -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnHoldFire;
                @Reload.started -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_PlayerActionActionsCallbackInterface.OnReload;
            }
            m_Wrapper.m_PlayerActionActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @TouchDragLook.started += instance.OnTouchDragLook;
                @TouchDragLook.performed += instance.OnTouchDragLook;
                @TouchDragLook.canceled += instance.OnTouchDragLook;
                @SingleFire.started += instance.OnSingleFire;
                @SingleFire.performed += instance.OnSingleFire;
                @SingleFire.canceled += instance.OnSingleFire;
                @HoldFire.started += instance.OnHoldFire;
                @HoldFire.performed += instance.OnHoldFire;
                @HoldFire.canceled += instance.OnHoldFire;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
            }
        }
    }
    public PlayerActionActions @PlayerAction => new PlayerActionActions(this);
    public interface IMouseActions
    {
        void OnMouseLook(InputAction.CallbackContext context);
    }
    public interface ITouchActions
    {
        void OnTouchDragLook(InputAction.CallbackContext context);
        void OnTouchSingleFire(InputAction.CallbackContext context);
        void OnTouchHoldFire(InputAction.CallbackContext context);
    }
    public interface IPlayerActionActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnTouchDragLook(InputAction.CallbackContext context);
        void OnSingleFire(InputAction.CallbackContext context);
        void OnHoldFire(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
    }
}
